---
title: "Day29"
author: "Dave Drennan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(tidyverse)
library(ggrepel)

```

```{r data}

cities <- st_read("data/day29/ne_110m_populated_places_simple.shp") %>%
  st_transform("ESRI:54030")

countries <- st_read("data/day29/ne_110m_admin_0_countries.shp") %>%
  st_transform("ESRI:54030")

largest <- c("Cairo", "Tokyo", "Istanbul", "Mexico City", "Melbourne", "São Paulo")

cities_largest <- cities %>%
  filter(name %in% largest)

ggplot()+
  geom_sf(data=countries, fill = "grey95", color = "grey80")+
  geom_sf(data=cities_largest, color = "red")+
  geom_sf_text(data=cities_largest, aes(label = name, hjust = 1), nudge_x = -300000, nudge_y = 0)+
  labs(title = "The Largest Cities by Population for Each Continent",
       caption = "Sources: Wikipedia, Natural Earth") +
  theme(legend.position = "none",
        panel.grid = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        plot.title=element_text(size=16,face="bold", color = "black", hjust = .5),
        plot.caption=element_text(size=10, color = "black"))

```
